# Generated by Django 5.2 on 2025-04-24 17:02

import TaskHero.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskHero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 4, 24), validators=[TaskHero.models.TaskModel.validate_due_date]),
        ),
    ]
